apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spa-frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spa-frontend
  template:
    metadata:
      labels:
        app: spa-frontend
        type: application
    spec:
      containers:
        - name: spa
          image: docker.io/jaydockship/spa:1.0.0
          imagePullPolicy: Always
          ports:
          - containerPort: 4200
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    run: frontend-service
spec:
  ports:
  - port: 4200
    protocol: TCP
  selector:
    app: spa-frontend
