resources:
- app1.yaml
- app2.yaml
- database.yaml
- ingress.yaml
- frontend.yaml
- nginx.yaml

configMapGenerator:
  ## option 1: sets data as the key: value pairs from file contents for the enviroment vars
  ##  usecase: use with envFrom in deployment.yaml
  - name: configmap-1
    envs:
      - app1.properties
  - name: configmap-2
    envs:
      - app2.properties

  ## option 2: sets data as the mapping of the file name to its corresponding contents
  ##  usecase: use alongside volumeMount in deployment.yaml
  # files:
  # - application.properties